# Generated by Django 4.1.1 on 2023-02-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexdjango', '0002_customuser_legendary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='legendary',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
