# Generated by Django 4.1.7 on 2023-03-13 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedexdjango', '0003_alter_customuser_legendary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favourite_pokemon',
            field=models.ManyToManyField(to='pokedexdjango.pokemon'),
        ),
    ]
